name: release-mirrors

on:
  release:
  workflow_dispatch:
    inputs:
      release_tag:
        description: Release tag (defaults to the tag of the release event)
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  getFiles:
    name: Get release files
    runs-on: ubuntu-latest
    steps:
      - name: Fetch release info
        id: fetchReleaseInfo
        run: |
          if [ -n "${{ inputs.release_tag }}" ]; then
            echo "release_tag=${{ inputs.release_tag }}" >> $GITHUB_ENV
          else
            gh release list --repo 'MaaAssistantArknights/MaaRelease' --limit 10 | tee ${{ runner.temp }}/release_maa
            head -n 1 ${{ runner.temp }}/release_maa | awk '{ print $1 }' > ${{ runner.temp }}/config

            echo "config:"
            cat ${{ runner.temp }}/config

            echo "release_tag=$(head -n 1 ${{ runner.temp }}/config)" >> $GITHUB_OUTPUT
            echo "randomUUID=$(uuidgen)" >> $GITHUB_OUTPUT
          fi
      - name: Download release
        run: |
          mkdir -pv ${{ runner.temp }}/upload-dir/${{ steps.fetchReleaseInfo.outputs.release_tag }}
          gh release download ${{ steps.fetchReleaseInfo.outputs.release_tag }} --repo 'MaaAssistantArknights/MaaRelease' --clobber --dir ${{ runner.temp }}/upload-dir/${{ steps.fetchReleaseInfo.outputs.release_tag }}
      - name: Save release files
        uses: actions/cache/save@v3
        with:
          path: ${{ runner.temp }}/upload-dir/${{ steps.fetchReleaseInfo.outputs.release_tag }}
          key: ${{ steps.fetchReleaseInfo.outputs.randomUUID }}
    outputs:
      release_tag: ${{ steps.fetchReleaseInfo.outputs.release_tag }}
      randomUUID: ${{ steps.fetchReleaseInfo.outputs.randomUUID }}

  mirror0:
    name: Upload to mirror 0
    runs-on: ubuntu-latest
    needs: getFiles
    # Disable it
    if: 1 == 0 && github.repository == 'MaaAssistantArknights/MaaRelease'
    steps:
      - name: Restore release files
        uses: actions/cache/restore@v3
        with:
          path: ${{ runner.temp }}/upload-dir/${{ needs.getFiles.outputs.release_tag }}
          key: ${{ needs.getFiles.outputs.randomUUID }}
      - name: Upload to mirror 0
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_MIRROR_0_HOST }}
          username: ${{ secrets.SSH_MIRROR_0_USER }}
          key: ${{ secrets.SSH_MIRROR_0_KEY }}
          source: ${{ runner.temp }}/upload-dir/${{ steps.fetchReleaseInfo.outputs.release_tag }}
          target: /data/html/MaaAssistantArknights/MaaRelease/releases/download
          strip_components: 1

  R2:
    name: Upload to R2
    runs-on: ubuntu-latest
    needs: getFiles
    if: github.repository == 'MaaAssistantArknights/MaaRelease'
    steps:
      - name: Restore release files
        uses: actions/cache/restore@v3
        with:
          path: ${{ runner.temp }}/upload-dir/${{ needs.getFiles.outputs.release_tag }}
          key: ${{ needs.getFiles.outputs.randomUUID }}
      - name: Upload to R2
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          SOURCE_DIR: ${{ runner.temp }}/upload-dir
          DEST_DIR: MaaAssistantArknights/MaaRelease/releases/download

  AnnAngelaCOS:
    name: Upload to AnnAngela's COS and fire webhook
    runs-on: ubuntu-latest
    needs: getFiles
    if: (github.repository == 'MaaAssistantArknights/MaaRelease' || github.repository == 'AnnAngela/MaaRelease') && !contains(needs.getFiles.outputs.release_tag, '.g')
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version: lts/*
          check-latest: true
          # cache: npm
      - name: Restore release files
        uses: actions/cache/restore@v3
        with:
          path: ${{ runner.temp }}/upload-dir/${{ needs.getFiles.outputs.release_tag }}
          key: ${{ needs.getFiles.outputs.randomUUID }}
      - name: Upload to AnnAngela's COS and fire webhook
        run: |
          echo "Installing coscli..."
          gh release download --pattern coscli-linux --dir ${{ runner.temp }}/coscli --clobber --repo tencentyun/coscli
          chmod +x ${{ runner.temp }}/coscli/coscli-linux
          echo "coscli installed."
          touch ~/.cos.yaml
          node .github/AnnAngela/prepare.js

  MAA_S3:
    name: Upload to MAA S3
    runs-on: ubuntu-latest
    needs: getFiles
    if: github.repository == 'MaaAssistantArknights/MaaRelease'
    steps:
      - name: Restore release files
        uses: actions/cache/restore@v3
        with:
          path: ${{ runner.temp }}/upload-dir/${{ needs.getFiles.outputs.release_tag }}
          key: ${{ needs.getFiles.outputs.randomUUID }}
      - name: Upload to MAA S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.MAA_MINIO_RELEASE_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.MAA_MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MAA_MINIO_SECRET_KEY }}
          AWS_REGION: us-east-1
          AWS_S3_ENDPOINT: ${{ secrets.MAA_MINIO_ENDPOINT }}
          SOURCE_DIR: ${{ runner.temp }}/upload-dir
          DEST_DIR: MaaAssistantArknights/MaaRelease/releases/download

  updateVersionApi:
    name: Dispatch the "update_version_api" workflow
    runs-on: ubuntu-latest
    needs:
      - mirror0
      - R2
      - AnnAngelaCOS
      - MAA_S3
    if: 1 == 0
    steps:
      - name: Dispatch the "update_version_api" workflow
        run: gh workflow run update_version_api

  deleteCache:
    name: Delete the cache
    runs-on: ubuntu-latest
    if: always() && contains(needs.getFiles.outputs.randomUUID, '-')
    needs:
      - getFiles
      - mirror0
      - R2
      - AnnAngelaCOS
      - MAA_S3
    steps:
      - name: Delete the cache
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete --confirm ${{ needs.getFiles.outputs.randomUUID }}
